
base_link: BODY

sensors:

  chains:
    larm_chain:
      root: CHEST_LINK1
      tip: LARM_LINK6
      cov:
       joint_angles: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
      gearing: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    rarm_chain:
      root: CHEST_LINK1
      tip: RARM_LINK6
      cov:
       joint_angles: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
      gearing: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    head_chain:
      root: CHEST_LINK1
      tip: HEAD_LINK1
      cov:
       joint_angles: [0.01, 0.01]
      gearing: [1.0, 1.0]
    torso_chain:
      root: BODY
      tip: CHEST_LINK1
      cov:
       joint_angles: [0.01, 0.01]
      gearing: [1.0, 1.0]
    lleg_chain:
      root: BODY
      tip: LLEG_LINK5 # LLEG_LINK6?
      cov:
       joint_angles: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
      gearing: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    rleg_chain:
      root: BODY
      tip: RLEG_LINK5 # RLEG_LINK6?
      cov:
       joint_angles: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
      gearing: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  rectified_cams:
    head_camera:
      chain_id: head_chain  #TODO: get rid of this
      frame_id: camera_rgb_optical_frame
      baseline_shift: 0.0
#      baseline_rgbd: 0.075 ## comment out if we run all_pipelines.launch with use_kinect
      f_shift: 0.0
      cx_shift: 0.0
      cy_shift: 0.0
      cov: {u: 0.25, v: 0.25, x: 0.25}

  tilting_lasers: {}

checkerboards:
  mmurooka_board_6x5:
    corners_x: 5
    corners_y: 6
    spacing_x: 0.03
    spacing_y: 0.03

transforms:
  arm_chain_cb:   [ .25, 0, 0, pi/2, 0, 0]
