analogs:
- !!python/tuple [176, 16]
- !!python/tuple [176, 17]
- !!python/tuple [176, 18]
- !!python/tuple [176, 19]
- !!python/tuple [176, 20]
- !!python/tuple [176, 21]
- !!python/tuple [176, 22]
- !!python/tuple [176, 23]
- !!python/tuple [176, 24]
- !!python/tuple [176, 60]
- !!python/tuple [176, 0]
- !!python/tuple [177, 0]
- !!python/tuple [178, 0]
- !!python/tuple [179, 0]
- !!python/tuple [180, 0]
- !!python/tuple [181, 0]
- !!python/tuple [182, 0]
- !!python/tuple [183, 0]
- !!python/tuple [184, 0]
buttons: [48, 49, 46, 47, 91, 92, 93, 94, 86, 95, 100, 24, 16, 8, 0, 25, 17, 9, 1,
  26, 18, 10, 2, 27, 19, 11, 3, 28, 20, 12, 4, 29, 21, 13, 5, 30, 22, 14, 6, 31, 23,
  15, 7, 78, 74, 75]
device_name: iCON iControls_Pro V1.02 MIDI 1
