analogs:
- !!python/tuple [144, 24]
- !!python/tuple [176, 16]
- !!python/tuple [144, 25]
- !!python/tuple [176, 17]
- !!python/tuple [144, 26]
- !!python/tuple [176, 18]
- !!python/tuple [144, 27]
- !!python/tuple [144, 18]
- !!python/tuple [176, 19]
- !!python/tuple [144, 28]
- !!python/tuple [176, 20]
- !!python/tuple [144, 29]
- !!python/tuple [176, 21]
- !!python/tuple [144, 30]
- !!python/tuple [176, 22]
- !!python/tuple [144, 31]
- !!python/tuple [176, 23]
- !!python/tuple [144, 97]
- !!python/tuple [144, 96]
- !!python/tuple [176, 60]
- !!python/tuple [144, 89]
- !!python/tuple [144, 104]
- !!python/tuple [224, 0]
- !!python/tuple [144, 105]
- !!python/tuple [224, 1]
- !!python/tuple [144, 106]
- !!python/tuple [224, 2]
- !!python/tuple [144, 107]
- !!python/tuple [224, 3]
- !!python/tuple [144, 108]
- !!python/tuple [224, 4]
- !!python/tuple [144, 109]
- !!python/tuple [224, 5]
- !!python/tuple [144, 110]
- !!python/tuple [224, 6]
- !!python/tuple [144, 111]
- !!python/tuple [224, 7]
- !!python/tuple [224, 8]
- !!python/tuple [144, 48]
- !!python/tuple [144, 49]
- !!python/tuple [144, 46]
- !!python/tuple [144, 47]
- !!python/tuple [144, 91]
- !!python/tuple [144, 92]
- !!python/tuple [144, 93]
- !!python/tuple [144, 94]
- !!python/tuple [144, 86]
- !!python/tuple [144, 95]
- !!python/tuple [144, 100]
- !!python/tuple [144, 16]
- !!python/tuple [144, 8]
- !!python/tuple [144, 0]
- !!python/tuple [144, 17]
- !!python/tuple [144, 9]
- !!python/tuple [144, 1]
- !!python/tuple [144, 10]
- !!python/tuple [144, 2]
- !!python/tuple [144, 19]
- !!python/tuple [144, 11]
- !!python/tuple [144, 3]
- !!python/tuple [144, 20]
- !!python/tuple [144, 12]
- !!python/tuple [144, 4]
- !!python/tuple [144, 21]
- !!python/tuple [144, 13]
- !!python/tuple [144, 5]
- !!python/tuple [144, 22]
- !!python/tuple [144, 14]
- !!python/tuple [144, 6]
- !!python/tuple [144, 23]
- !!python/tuple [144, 15]
- !!python/tuple [144, 7]
- !!python/tuple [144, 78]
- !!python/tuple [144, 74]
- !!python/tuple [144, 75]
buttons: []
device_name: iCON iControls_Pro V1.02 MIDI 1
