analogs:
- !!python/tuple [176, 12]
- !!python/tuple [176, 29]
- !!python/tuple [176, 71]
- !!python/tuple [176, 72]
- !!python/tuple [176, 5]
- !!python/tuple [176, 1]
- !!python/tuple [176, 18]
- !!python/tuple [176, 77]
- !!python/tuple [176, 82]
- !!python/tuple [176, 14]
- !!python/tuple [176, 19]
- !!python/tuple [176, 15]
- !!python/tuple [176, 22]
- !!python/tuple [176, 74]
- !!python/tuple [144, 77]
- !!python/tuple [144, 79]
- !!python/tuple [144, 82]
- !!python/tuple [144, 84]
- !!python/tuple [144, 67]
- !!python/tuple [144, 70]
- !!python/tuple [144, 72]
- !!python/tuple [144, 75]
- !!python/tuple [144, 58]
- !!python/tuple [144, 60]
- !!python/tuple [144, 63]
- !!python/tuple [144, 65]
- !!python/tuple [144, 48]
- !!python/tuple [144, 51]
- !!python/tuple [144, 53]
- !!python/tuple [144, 55]
- !!python/tuple [176, 90]
- !!python/tuple [176, 91]
- !!python/tuple [176, 92]
buttons: []
device_name: QUNEO MIDI 1
